// This file is automatically generated. Do not modify it manually.
import { useMemo } from 'react';

// A hook to memoize Firebase queries.
export function useMemoFirebase<T>(
  factory: () => T,
  deps: React.DependencyList
): T {
  // eslint-disable-next-line react-hooks/exhaustive-deps
  return useMemo(factory, deps);
}
