// This file is automatically generated. Do not modify it manually.
import { useMemo, DependencyList } from 'react';

type MemoFirebase<T> = T & { __memo?: boolean };

// A hook to memoize Firebase queries.
export function useMemoFirebase<T>(
  factory: () => T,
  deps: DependencyList
): T | (MemoFirebase<T>) {
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const memoized = useMemo(factory, deps);
  
  if (typeof memoized !== 'object' || memoized === null) return memoized;
  (memoized as MemoFirebase<T>).__memo = true;
  
  return memoized;
}