// This file is automatically generated. Do not modify it manually.
'use client';

import React, { useMemo } from 'react';
import { FirebaseProvider } from './provider';
import { initializeFirebase } from '.';

export function FirebaseClientProvider({
  children,
}: React.PropsWithChildren<{}>) {
  const useEmulators = process.env.NEXT_PUBLIC_USE_FIREBASE_EMULATORS === 'true';

  const { firebaseApp, auth, firestore, storage } = useMemo(
    () => initializeFirebase({ useEmulators }),
    [useEmulators]
  );
  return (
    <FirebaseProvider firebaseApp={firebaseApp} auth={auth} firestore={firestore} storage={storage}>
      {children}
    </FirebaseProvider>
  );
}
