// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "projectId": "studio-5677141605-2f192",
  "appId": "1:151238957712:web:f55984374f9d3f1aa9d615",
  "apiKey": "AIzaSyBQD3ZYvCpksG_dywG_P5GmS77h08P59uo",
  "authDomain": "studio-5677141605-2f192.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "151238957712"
};
