// This file is automatically generated. Do not modify it manually.
import { FirebaseError } from "firebase/app";

export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete' | 'write';
  requestResourceData?: any;
};

export class FirestorePermissionError extends FirebaseError {
  public readonly context: SecurityRuleContext;

  constructor(context: SecurityRuleContext) {
    const message = `FirestoreError: Missing or insufficient permissions: The following request was denied by Firestore Security Rules:
${JSON.stringify({ ...context }, null, 2)}`;
    super('permission-denied', message);
    this.name = 'FirestorePermissionError';
    this.context = context;
  }
}
