// This file is automatically generated. Do not modify it manually.
'use client';
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';
import { getStorage, FirebaseStorage } from 'firebase/storage';

import { firebaseConfig } from './config';

import { useFirebase } from './provider';
import { useCollection } from './firestore/use-collection';
import { useDoc } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import { useMemoFirebase } from '../lib/use-memo-firebase';
import { useUserProfile } from './user-profile-provider';

export {
  useFirebase,
  useCollection,
  useDoc,
  useUser,
  useUserProfile,
  useMemoFirebase,
  firebaseConfig,
};
export * from './provider';
export { FirebaseClientProvider } from './client-provider';

let firebaseApp: FirebaseApp;
let auth: Auth;
let firestore: Firestore;
let storage: FirebaseStorage;

/**
 * Initializes Firebase services as singletons to prevent "Unexpected state" errors
 * caused by multiple service instances competing for local state.
 */
export function initializeFirebase({ useEmulators = false } = {}) {
  if (!firebaseApp) {
    if (getApps().length > 0) {
      firebaseApp = getApp();
    } else {
      firebaseApp = initializeApp(firebaseConfig);
    }
  }
  
  if (!auth) auth = getAuth(firebaseApp);
  if (!firestore) firestore = getFirestore(firebaseApp);
  if (!storage) storage = getStorage(firebaseApp);

  return { firebaseApp, auth, firestore, storage };
}
