// This file is automatically generated. Do not modify it manually.
'use client';
import { useMemo } from 'react';
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, Auth } from 'firebase/auth';
import {
  getFirestore,
  connectFirestoreEmulator,
  Firestore,
} from 'firebase/firestore';

import { firebaseConfig } from './config';

import { useFirebase } from './provider';
import { useCollection } from './firestore/use-collection';
import { useDoc } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import { useMemoFirebase } from '../lib/use-memo-firebase';
import { useUserProfile } from './user-profile-provider';

export {
  useFirebase,
  useCollection,
  useDoc,
  useUser,
  useUserProfile,
  useMemoFirebase,
  firebaseConfig,
};
export * from './provider';
export { FirebaseClientProvider } from './client-provider';

let firebaseApp: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

const EMULATORS_STARTED = 'EMULATORS_STARTED';
function startEmulators() {
  if (!(global as any)[EMULATORS_STARTED]) {
    (global as any)[EMULATORS_STARTED] = true;
    connectAuthEmulator(auth, 'http://127.0.0.1:9099', {
      disableWarnings: true,
    });
    connectFirestoreEmulator(firestore, '127.0.0.1', 8080);
  }
}

export function initializeFirebase(options: { useEmulators: boolean } = { useEmulators: false }) {
  const isInitialized = getApps().length > 0;
  firebaseApp = isInitialized ? getApp() : initializeApp(firebaseConfig);
  auth = getAuth(firebaseApp);
  firestore = getFirestore(firebaseApp);

  if (options.useEmulators) {
    startEmulators();
  }

  return { firebaseApp, auth, firestore };
}
