// This file is automatically generated. Do not modify it manually.
'use client';
import { useEffect } from 'react';
import { errorEmitter } from '../firebase/error-emitter';
import { FirestorePermissionError } from '../firebase/errors';

export function FirebaseErrorListener() {
  useEffect(() => {
    const handlePermissionError = (error: FirestorePermissionError) => {
      // For developers, we want to throw this so that Next.js can
      // show the error overlay. This is much more visible than a console.log.
      if (process.env.NODE_ENV === 'development') {
        throw error;
      }
    };
    errorEmitter.on('permission-error', handlePermissionError);
    return () => {
      errorEmitter.off('permission-error', handlePermissionError);
    };
  }, []);
  return null;
}
