/**
 * @fileOverview Master Catalog Seed Data: Segment 1
 */

export const seedPart1: any[] = [
  {
    "id": "seed-0001",
    "name": "Zenith Dyson Relic",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 375.09,
    "retailPrice": 1036.84,
    "stockLevel": 219,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-2",
    "tags": ["Zenith", "Relic", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815515"
  },
  {
    "id": "seed-0002",
    "name": "Nomad Cashmere Throw Chronograph",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 620.36,
    "retailPrice": 1613.75,
    "stockLevel": 190,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-6",
    "tags": ["Nomad", "Chronograph", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815538"
  },
  {
    "id": "seed-0003",
    "name": "Nomad Cashmere Throw Folio",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 538.41,
    "retailPrice": 1373.32,
    "stockLevel": 85,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Nomad", "Folio", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815549"
  },
  {
    "id": "seed-0004",
    "name": "Radiant Cashmere Throw Enclave",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 210.51,
    "retailPrice": 557.23,
    "stockLevel": 64,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-14",
    "tags": ["Radiant", "Enclave", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815586"
  },
  {
    "id": "seed-0005",
    "name": "Radiant Apple Decanter",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 633.62,
    "retailPrice": 1292.09,
    "stockLevel": 17,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-3",
    "tags": ["Radiant", "Decanter", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815603"
  },
  {
    "id": "seed-0006",
    "name": "Kinetic Chopard Decanter",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 256.64,
    "retailPrice": 703.15,
    "stockLevel": 78,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-1",
    "tags": ["Kinetic", "Decanter", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815769"
  },
  {
    "id": "seed-0007",
    "name": "Nomad Casio G-Shock Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 78.84,
    "retailPrice": 180.94,
    "stockLevel": 43,
    "categories": ["Watches"],
    "imageId": "demo-watches-8",
    "tags": ["Nomad", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815783"
  },
  {
    "id": "seed-0008",
    "name": "Sovereign Diffuser Edition",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 39.86,
    "retailPrice": 95.56,
    "stockLevel": 240,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-12",
    "tags": ["Sovereign", "Edition", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815799"
  },
  {
    "id": "seed-0009",
    "name": "Obsidian Seiko Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 544.74,
    "retailPrice": 1263.17,
    "stockLevel": 200,
    "categories": ["Watches"],
    "imageId": "demo-watches-14",
    "tags": ["Obsidian", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815813"
  },
  {
    "id": "seed-0010",
    "name": "Kinetic Diffuser Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 431.25,
    "retailPrice": 1017.6,
    "stockLevel": 254,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-6",
    "tags": ["Kinetic", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815822"
  },
  {
    "id": "seed-0011",
    "name": "Sovereign Smart Lighting Decanter",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 160.91,
    "retailPrice": 450.19,
    "stockLevel": 57,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-4",
    "tags": ["Sovereign", "Decanter", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815830"
  },
  {
    "id": "seed-0012",
    "name": "Obsidian Marble Sculpture Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 385.86,
    "retailPrice": 1055.42,
    "stockLevel": 219,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-10",
    "tags": ["Obsidian", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815839"
  },
  {
    "id": "seed-0013",
    "name": "Imperial Monogrammed Tote Relic",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 465.64,
    "retailPrice": 1090.96,
    "inventory": 44,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-15",
    "tags": ["Imperial", "Relic", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815848"
  },
  {
    "id": "seed-0014",
    "name": "Zenith Cashmere Throw Relic",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 242.26,
    "retailPrice": 611.55,
    "stockLevel": 111,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-7",
    "tags": ["Zenith", "Relic", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815856"
  },
  {
    "id": "seed-0015",
    "name": "Gilded Diffuser Relic",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 571.6,
    "retailPrice": 1030.85,
    "stockLevel": 222,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-14",
    "tags": ["Gilded", "Relic", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815865"
  },
  {
    "id": "seed-0016",
    "name": "Kinetic Tissot Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 457.8,
    "retailPrice": 970.51,
    "stockLevel": 12,
    "categories": ["Watches"],
    "imageId": "demo-watches-13",
    "tags": ["Kinetic", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815873"
  },
  {
    "id": "seed-0017",
    "name": "Kinetic Carnelian Pendant",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 588.09,
    "retailPrice": 1429.85,
    "stockLevel": 54,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-1",
    "tags": ["Kinetic", "Pendant", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815882"
  },
  {
    "id": "seed-0018",
    "name": "Kinetic Italian Briefcase Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 353.07,
    "retailPrice": 936.77,
    "stockLevel": 210,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-2",
    "tags": ["Kinetic", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815890"
  },
  {
    "id": "seed-0019",
    "name": "Kinetic Diffuser Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 620.67,
    "retailPrice": 1621.32,
    "stockLevel": 12,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-3",
    "tags": ["Kinetic", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815900"
  },
  {
    "id": "seed-0020",
    "name": "Nomad Carnelian Enclave",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 213.46,
    "retailPrice": 522.3,
    "stockLevel": 25,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-14",
    "tags": ["Nomad", "Enclave", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815908"
  },
  {
    "id": "seed-0021",
    "name": "Obsidian Tissot Artifact",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 375.89,
    "retailPrice": 968.17,
    "stockLevel": 240,
    "categories": ["Watches"],
    "imageId": "demo-watches-6",
    "tags": ["Obsidian", "Artifact", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815916"
  },
  {
    "id": "seed-0022",
    "name": "Radiant Lego Architecture Legacy",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 309.72,
    "retailPrice": 664.67,
    "stockLevel": 24,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-6",
    "tags": ["Radiant", "Legacy", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815925"
  },
  {
    "id": "seed-0023",
    "name": "Kinetic Ethical Gold Edition",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 484.34,
    "retailPrice": 1339.49,
    "stockLevel": 176,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-3",
    "tags": ["Kinetic", "Edition", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815937"
  },
  {
    "id": "seed-0024",
    "name": "Celestial Limited Lithograph Artifact",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 503.1,
    "retailPrice": 1098.12,
    "stockLevel": 220,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-11",
    "tags": ["Celestial", "Artifact", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815948"
  },
  {
    "id": "seed-0025",
    "name": "Nomad Apple Pendant",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 101.69,
    "retailPrice": 197.37,
    "stockLevel": 246,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-11",
    "tags": ["Nomad", "Pendant", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815957"
  },
  {
    "id": "seed-0026",
    "name": "Elysian Monogrammed Tote Enclave",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 344.72,
    "retailPrice": 834.31,
    "stockLevel": 183,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-14",
    "tags": ["Elysian", "Enclave", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815966"
  },
  {
    "id": "seed-0027",
    "name": "Sovereign Carnelian Legacy",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 177.78,
    "retailPrice": 368.72,
    "stockLevel": 83,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-5",
    "tags": ["Sovereign", "Legacy", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815974"
  },
  {
    "id": "seed-0028",
    "name": "Obsidian Cuyana Vessel",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 363.47,
    "retailPrice": 891.48,
    "stockLevel": 38,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-3",
    "tags": ["Obsidian", "Vessel", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815985"
  },
  {
    "id": "seed-0029",
    "name": "Radiant Sony Legacy",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 99.46,
    "retailPrice": 208.57,
    "stockLevel": 188,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-10",
    "tags": ["Radiant", "Legacy", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815996"
  },
  {
    "id": "seed-0030",
    "name": "Zenith Toiletry Set Chronograph",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 529.57,
    "retailPrice": 1076.31,
    "stockLevel": 232,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-10",
    "tags": ["Zenith", "Chronograph", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816004"
  },
  {
    "id": "seed-0031",
    "name": "Radiant Smart Lighting Decanter",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 459.41,
    "retailPrice": 929.61,
    "stockLevel": 80,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Radiant", "Decanter", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816013"
  },
  {
    "id": "seed-0032",
    "name": "Celestial Canvas Print Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 165.94,
    "retailPrice": 327.13,
    "stockLevel": 211,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-9",
    "tags": ["Celestial", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816021"
  },
  {
    "id": "seed-0033",
    "name": "Celestial Toiletry Set Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 32.71,
    "retailPrice": 66.66,
    "stockLevel": 27,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Celestial", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816029"
  },
  {
    "id": "seed-0034",
    "name": "Gilded Apple Folio",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 316.74,
    "retailPrice": 681.34,
    "stockLevel": 210,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-4",
    "tags": ["Gilded", "Folio", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816037"
  },
  {
    "id": "seed-0035",
    "name": "Nomad Cashmere Throw Chronograph",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 239.51,
    "retailPrice": 505.55,
    "stockLevel": 177,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-1",
    "tags": ["Nomad", "Chronograph", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816045"
  }
];
