/**
 * @fileOverview Master Catalog Seed Data: Segment 1 (Items 0001 - 0105)
 */

export const seedPart1: any[] = [
  {
    "id": "seed-0001",
    "name": "Zenith Dyson Relic",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 375.09,
    "retailPrice": 1036.84,
    "stockLevel": 219,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-2",
    "tags": ["Zenith", "Relic", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815515"
  },
  {
    "id": "seed-0002",
    "name": "Nomad Cashmere Throw Chronograph",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 620.36,
    "retailPrice": 1613.75,
    "stockLevel": 190,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-6",
    "tags": ["Nomad", "Chronograph", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815538"
  },
  {
    "id": "seed-0003",
    "name": "Nomad Cashmere Throw Folio",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 538.41,
    "retailPrice": 1373.32,
    "stockLevel": 85,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Nomad", "Folio", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815549"
  },
  {
    "id": "seed-0004",
    "name": "Radiant Cashmere Throw Enclave",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 210.51,
    "retailPrice": 557.23,
    "stockLevel": 64,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-14",
    "tags": ["Radiant", "Enclave", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815586"
  },
  {
    "id": "seed-0005",
    "name": "Radiant Apple Decanter",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 633.62,
    "retailPrice": 1292.09,
    "stockLevel": 17,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-3",
    "tags": ["Radiant", "Decanter", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815603"
  },
  {
    "id": "seed-0006",
    "name": "Kinetic Chopard Decanter",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 256.64,
    "retailPrice": 703.15,
    "stockLevel": 78,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-1",
    "tags": ["Kinetic", "Decanter", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815769"
  },
  {
    "id": "seed-0007",
    "name": "Nomad Casio G-Shock Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 78.84,
    "retailPrice": 180.94,
    "stockLevel": 43,
    "categories": ["Watches"],
    "imageId": "demo-watches-8",
    "tags": ["Nomad", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815783"
  },
  {
    "id": "seed-0008",
    "name": "Sovereign Diffuser Edition",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 39.86,
    "retailPrice": 95.56,
    "stockLevel": 240,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-12",
    "tags": ["Sovereign", "Edition", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815799"
  },
  {
    "id": "seed-0009",
    "name": "Obsidian Seiko Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 544.74,
    "retailPrice": 1263.17,
    "stockLevel": 200,
    "categories": ["Watches"],
    "imageId": "demo-watches-14",
    "tags": ["Obsidian", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815813"
  },
  {
    "id": "seed-0010",
    "name": "Kinetic Diffuser Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 431.25,
    "retailPrice": 1017.6,
    "stockLevel": 254,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-6",
    "tags": ["Kinetic", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815822"
  },
  {
    "id": "seed-0011",
    "name": "Sovereign Smart Lighting Decanter",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 160.91,
    "retailPrice": 450.19,
    "stockLevel": 57,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-4",
    "tags": ["Sovereign", "Decanter", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815830"
  },
  {
    "id": "seed-0012",
    "name": "Obsidian Marble Sculpture Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 385.86,
    "retailPrice": 1055.42,
    "stockLevel": 219,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-10",
    "tags": ["Obsidian", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815839"
  },
  {
    "id": "seed-0013",
    "name": "Imperial Monogrammed Tote Relic",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 465.64,
    "retailPrice": 1090.96,
    "stockLevel": 44,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-15",
    "tags": ["Imperial", "Relic", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815848"
  },
  {
    "id": "seed-0014",
    "name": "Zenith Cashmere Throw Relic",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 242.26,
    "retailPrice": 611.55,
    "stockLevel": 111,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-7",
    "tags": ["Zenith", "Relic", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815856"
  },
  {
    "id": "seed-0015",
    "name": "Gilded Diffuser Relic",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 571.6,
    "retailPrice": 1030.85,
    "stockLevel": 222,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-14",
    "tags": ["Gilded", "Relic", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815865"
  },
  {
    "id": "seed-0016",
    "name": "Kinetic Tissot Enclave",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 457.8,
    "retailPrice": 970.51,
    "stockLevel": 12,
    "categories": ["Watches"],
    "imageId": "demo-watches-13",
    "tags": ["Kinetic", "Enclave", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815873"
  },
  {
    "id": "seed-0017",
    "name": "Kinetic Carnelian Pendant",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 588.09,
    "retailPrice": 1429.85,
    "stockLevel": 54,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-1",
    "tags": ["Kinetic", "Pendant", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815882"
  },
  {
    "id": "seed-0018",
    "name": "Kinetic Italian Briefcase Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 353.07,
    "retailPrice": 936.77,
    "stockLevel": 210,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-2",
    "tags": ["Kinetic", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815890"
  },
  {
    "id": "seed-0019",
    "name": "Kinetic Diffuser Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 620.67,
    "retailPrice": 1621.32,
    "stockLevel": 12,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-3",
    "tags": ["Kinetic", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815900"
  },
  {
    "id": "seed-0020",
    "name": "Nomad Carnelian Enclave",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 213.46,
    "retailPrice": 522.3,
    "stockLevel": 25,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-14",
    "tags": ["Nomad", "Enclave", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815908"
  },
  {
    "id": "seed-0021",
    "name": "Obsidian Tissot Artifact",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 375.89,
    "retailPrice": 968.17,
    "stockLevel": 240,
    "categories": ["Watches"],
    "imageId": "demo-watches-6",
    "tags": ["Obsidian", "Artifact", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815916"
  },
  {
    "id": "seed-0022",
    "name": "Radiant Lego Architecture Legacy",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 309.72,
    "retailPrice": 664.67,
    "stockLevel": 24,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-6",
    "tags": ["Radiant", "Legacy", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815925"
  },
  {
    "id": "seed-0023",
    "name": "Kinetic Ethical Gold Edition",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 484.34,
    "retailPrice": 1339.49,
    "stockLevel": 176,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-3",
    "tags": ["Kinetic", "Edition", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815937"
  },
  {
    "id": "seed-0024",
    "name": "Celestial Limited Lithograph Artifact",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 503.1,
    "retailPrice": 1098.12,
    "stockLevel": 220,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-11",
    "tags": ["Celestial", "Artifact", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815948"
  },
  {
    "id": "seed-0025",
    "name": "Nomad Apple Pendant",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 101.69,
    "retailPrice": 197.37,
    "stockLevel": 246,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-11",
    "tags": ["Nomad", "Pendant", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815957"
  },
  {
    "id": "seed-0026",
    "name": "Elysian Monogrammed Tote Enclave",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 344.72,
    "retailPrice": 834.31,
    "stockLevel": 183,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-14",
    "tags": ["Elysian", "Enclave", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815966"
  },
  {
    "id": "seed-0027",
    "name": "Sovereign Carnelian Legacy",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 177.78,
    "retailPrice": 368.72,
    "stockLevel": 83,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-5",
    "tags": ["Sovereign", "Legacy", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815974"
  },
  {
    "id": "seed-0028",
    "name": "Obsidian Cuyana Vessel",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 363.47,
    "retailPrice": 891.48,
    "stockLevel": 38,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-3",
    "tags": ["Obsidian", "Vessel", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815985"
  },
  {
    "id": "seed-0029",
    "name": "Radiant Sony Legacy",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 99.46,
    "retailPrice": 208.57,
    "stockLevel": 188,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-10",
    "tags": ["Radiant", "Legacy", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.815996"
  },
  {
    "id": "seed-0030",
    "name": "Zenith Toiletry Set Chronograph",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 529.57,
    "retailPrice": 1076.31,
    "stockLevel": 232,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-10",
    "tags": ["Zenith", "Chronograph", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816004"
  },
  {
    "id": "seed-0031",
    "name": "Radiant Smart Lighting Decanter",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 459.41,
    "retailPrice": 929.61,
    "stockLevel": 80,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Radiant", "Decanter", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816013"
  },
  {
    "id": "seed-0032",
    "name": "Celestial Canvas Print Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 165.94,
    "retailPrice": 327.13,
    "stockLevel": 211,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-9",
    "tags": ["Celestial", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816021"
  },
  {
    "id": "seed-0033",
    "name": "Celestial Toiletry Set Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 32.71,
    "retailPrice": 66.66,
    "stockLevel": 27,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Celestial", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816029"
  },
  {
    "id": "seed-0034",
    "name": "Gilded Apple Folio",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 316.74,
    "retailPrice": 681.34,
    "stockLevel": 210,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-4",
    "tags": ["Gilded", "Folio", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816037"
  },
  {
    "id": "seed-0035",
    "name": "Nomad Cashmere Throw Chronograph",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 239.51,
    "retailPrice": 505.55,
    "stockLevel": 177,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-1",
    "tags": ["Nomad", "Chronograph", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:09:55.816045"
  },
  {
    "id": "seed-0036",
    "name": "Gilded Italian Briefcase Edition",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 503.56,
    "retailPrice": 1310.47,
    "stockLevel": 232,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-14",
    "tags": ["Gilded", "Edition", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059186"
  },
  {
    "id": "seed-0037",
    "name": "Zenith Canvas Print Edition",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 26.84,
    "retailPrice": 57.69,
    "stockLevel": 14,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-13",
    "tags": ["Zenith", "Edition", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059206"
  },
  {
    "id": "seed-0038",
    "name": "Kinetic Diamond Studs Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 88.24,
    "retailPrice": 207.21,
    "stockLevel": 142,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-6",
    "tags": ["Kinetic", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059217"
  },
  {
    "id": "seed-0039",
    "name": "Elysian Marble Sculpture Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 250.94,
    "retailPrice": 526.97,
    "stockLevel": 106,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-9",
    "tags": ["Elysian", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059226"
  },
  {
    "id": "seed-0040",
    "name": "Celestial Dyson Artifact",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 385.09,
    "retailPrice": 1060.6,
    "stockLevel": 259,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-2",
    "tags": ["Celestial", "Artifact", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059234"
  },
  {
    "id": "seed-0041",
    "name": "Nomad Vintage Comic Edition",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 78.59,
    "retailPrice": 188.24,
    "stockLevel": 68,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-2",
    "tags": ["Nomad", "Edition", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059242"
  },
  {
    "id": "seed-0042",
    "name": "Celestial Chopard Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 322.93,
    "retailPrice": 589.91,
    "stockLevel": 50,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-8",
    "tags": ["Celestial", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059249"
  },
  {
    "id": "seed-0043",
    "name": "Kinetic Toiletry Set Enclave",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 466.9,
    "retailPrice": 1213.17,
    "stockLevel": 45,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-8",
    "tags": ["Kinetic", "Enclave", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059259"
  },
  {
    "id": "seed-0044",
    "name": "Elysian Hand-blown Glass Edition",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 374.53,
    "retailPrice": 878.46,
    "stockLevel": 153,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-8",
    "tags": ["Elysian", "Edition", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059271"
  },
  {
    "id": "seed-0045",
    "name": "Elysian Marble Sculpture Enclave",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 222.07,
    "retailPrice": 536.86,
    "stockLevel": 242,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-3",
    "tags": ["Elysian", "Enclave", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059278"
  },
  {
    "id": "seed-0046",
    "name": "Imperial Ceramic Set Edition",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 233.78,
    "retailPrice": 638.16,
    "stockLevel": 35,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Imperial", "Edition", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059285"
  },
  {
    "id": "seed-0047",
    "name": "Celestial Canvas Print Enclave",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 167.88,
    "retailPrice": 416.11,
    "stockLevel": 23,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-8",
    "tags": ["Celestial", "Enclave", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059292"
  },
  {
    "id": "seed-0048",
    "name": "Gilded Cashmere Throw Relic",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 31.75,
    "retailPrice": 78.38,
    "stockLevel": 64,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Gilded", "Relic", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059299"
  },
  {
    "id": "seed-0049",
    "name": "Gilded Ceramic Set Edition",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 181.53,
    "retailPrice": 453.32,
    "stockLevel": 133,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-10",
    "tags": ["Gilded", "Edition", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059305"
  },
  {
    "id": "seed-0050",
    "name": "Imperial Ceramic Set Enclave",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 431.31,
    "retailPrice": 1022.85,
    "stockLevel": 233,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-6",
    "tags": ["Imperial", "Enclave", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059312"
  },
  {
    "id": "seed-0051",
    "name": "Radiant Vintage Comic Chronograph",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 14.63,
    "retailPrice": 31.04,
    "stockLevel": 102,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-15",
    "tags": ["Radiant", "Chronograph", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059318"
  },
  {
    "id": "seed-0052",
    "name": "Sovereign Tennis Bracelet Pendant",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 39.38,
    "retailPrice": 98.48,
    "stockLevel": 237,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-7",
    "tags": ["Sovereign", "Pendant", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059325"
  },
  {
    "id": "seed-0053",
    "name": "Zenith Vintage Comic Artifact",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 121.74,
    "retailPrice": 283.86,
    "stockLevel": 119,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-8",
    "tags": ["Zenith", "Artifact", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059340"
  },
  {
    "id": "seed-0054",
    "name": "Obsidian Marble Sculpture Pendant",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 258.05,
    "retailPrice": 639.59,
    "stockLevel": 43,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-9",
    "tags": ["Obsidian", "Pendant", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059350"
  },
  {
    "id": "seed-0055",
    "name": "Obsidian Casio G-Shock Edition",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 612.73,
    "retailPrice": 1231.3,
    "stockLevel": 238,
    "categories": ["Watches"],
    "imageId": "demo-watches-11",
    "tags": ["Obsidian", "Edition", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059361"
  },
  {
    "id": "seed-0056",
    "name": "Imperial Canvas Print Artifact",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 738.69,
    "retailPrice": 1745.8,
    "stockLevel": 132,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-5",
    "tags": ["Imperial", "Artifact", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059368"
  },
  {
    "id": "seed-0057",
    "name": "Obsidian Chopard Relic",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 479.31,
    "retailPrice": 1058.31,
    "stockLevel": 235,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-15",
    "tags": ["Obsidian", "Relic", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059375"
  },
  {
    "id": "seed-0058",
    "name": "Kinetic Cuyana Vessel",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 502.64,
    "retailPrice": 1035.66,
    "stockLevel": 102,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Kinetic", "Vessel", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059381"
  },
  {
    "id": "seed-0059",
    "name": "Radiant Smart Lighting Enclave",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 562.6,
    "retailPrice": 1123.79,
    "stockLevel": 216,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-15",
    "tags": ["Radiant", "Enclave", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059390"
  },
  {
    "id": "seed-0060",
    "name": "Kinetic Ethical Gold Edition",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 64.55,
    "retailPrice": 160.98,
    "stockLevel": 162,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-2",
    "tags": ["Kinetic", "Edition", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059399"
  },
  {
    "id": "seed-0061",
    "name": "Zenith Vintage Omega Folio",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 91.35,
    "retailPrice": 232.83,
    "stockLevel": 99,
    "categories": ["Watches"],
    "imageId": "demo-watches-12",
    "tags": ["Zenith", "Folio", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059405"
  },
  {
    "id": "seed-0062",
    "name": "Radiant Lego Architecture Folio",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 436.02,
    "retailPrice": 1219.53,
    "stockLevel": 68,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-9",
    "tags": ["Radiant", "Folio", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059412"
  },
  {
    "id": "seed-0063",
    "name": "Zenith Ethical Gold Enclave",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 332.87,
    "retailPrice": 826.62,
    "stockLevel": 199,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-1",
    "tags": ["Zenith", "Enclave", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059419"
  },
  {
    "id": "seed-0064",
    "name": "Sovereign Toiletry Set Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 581.43,
    "retailPrice": 1548.61,
    "stockLevel": 163,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-14",
    "tags": ["Sovereign", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059428"
  },
  {
    "id": "seed-0065",
    "name": "Obsidian Seiko Decanter",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 638.14,
    "retailPrice": 1746.37,
    "stockLevel": 237,
    "categories": ["Watches"],
    "imageId": "demo-watches-14",
    "tags": ["Obsidian", "Decanter", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059435"
  },
  {
    "id": "seed-0066",
    "name": "Celestial Chopard Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 534.83,
    "retailPrice": 1283.91,
    "stockLevel": 35,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-10",
    "tags": ["Celestial", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059441"
  },
  {
    "id": "seed-0067",
    "name": "Zenith Cashmere Throw Pendant",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 462.12,
    "retailPrice": 1015.15,
    "stockLevel": 142,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-12",
    "tags": ["Zenith", "Pendant", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059447"
  },
  {
    "id": "seed-0068",
    "name": "Kinetic Apple Chronograph",
    "description": "A premium Tech & Electronics asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 614.36,
    "retailPrice": 1687.18,
    "stockLevel": 48,
    "categories": ["Tech & Electronics"],
    "imageId": "demo-tech-&-electronics-6",
    "tags": ["Kinetic", "Chronograph", "Tech & Electronics", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059454"
  },
  {
    "id": "seed-0069",
    "name": "Imperial Smart Lighting Folio",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 726.92,
    "retailPrice": 1330.56,
    "stockLevel": 48,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-4",
    "tags": ["Imperial", "Folio", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059461"
  },
  {
    "id": "seed-0070",
    "name": "Gilded Diamond Studs Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 583.11,
    "retailPrice": 1580.17,
    "stockLevel": 37,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-2",
    "tags": ["Gilded", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:43:29.059467"
  },
  {
    "id": "seed-0071",
    "name": "Kinetic Vintage Omega Folio",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 91.85,
    "retailPrice": 209,
    "stockLevel": 72,
    "categories": ["Watches"],
    "imageId": "demo-watches-12",
    "tags": ["Kinetic", "Folio", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581599"
  },
  {
    "id": "seed-0072",
    "name": "Radiant Lego Architecture Decanter",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 539.38,
    "retailPrice": 1033.36,
    "stockLevel": 99,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-5",
    "tags": ["Radiant", "Decanter", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581618"
  },
  {
    "id": "seed-0073",
    "name": "Radiant Vintage Omega Folio",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 474.83,
    "retailPrice": 1107.93,
    "stockLevel": 35,
    "categories": ["Watches"],
    "imageId": "demo-watches-12",
    "tags": ["Radiant", "Folio", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581627"
  },
  {
    "id": "seed-0074",
    "name": "Celestial Diamond Studs Edition",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 412.77,
    "retailPrice": 1085.09,
    "stockLevel": 255,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-5",
    "tags": ["Celestial", "Edition", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581634"
  },
  {
    "id": "seed-0075",
    "name": "Obsidian Limited Lithograph Edition",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 186.81,
    "retailPrice": 428.62,
    "stockLevel": 126,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-4",
    "tags": ["Obsidian", "Edition", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581641"
  },
  {
    "id": "seed-0076",
    "name": "Obsidian Vintage Comic Vessel",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 198.29,
    "retailPrice": 359.34,
    "stockLevel": 254,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-15",
    "tags": ["Obsidian", "Vessel", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581649"
  },
  {
    "id": "seed-0077",
    "name": "Sovereign Monogrammed Tote Vessel",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 293.85,
    "retailPrice": 627.35,
    "stockLevel": 22,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-12",
    "tags": ["Sovereign", "Vessel", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581655"
  },
  {
    "id": "seed-0078",
    "name": "Nomad Marble Sculpture Chronograph",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 260.5,
    "retailPrice": 674.79,
    "stockLevel": 129,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-3",
    "tags": ["Nomad", "Chronograph", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581662"
  },
  {
    "id": "seed-0079",
    "name": "Gilded Diffuser Enclave",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 109.96,
    "retailPrice": 258.87,
    "stockLevel": 44,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-2",
    "tags": ["Gilded", "Enclave", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581676"
  },
  {
    "id": "seed-0080",
    "name": "Nomad Hamilton Folio",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 230.13,
    "retailPrice": 425.77,
    "stockLevel": 160,
    "categories": ["Watches"],
    "imageId": "demo-watches-7",
    "tags": ["Nomad", "Folio", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581683"
  },
  {
    "id": "seed-0081",
    "name": "Radiant Limited Lithograph Enclave",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 369.59,
    "retailPrice": 683.18,
    "stockLevel": 25,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-11",
    "tags": ["Radiant", "Enclave", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581689"
  },
  {
    "id": "seed-0082",
    "name": "Sovereign Diffuser Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 566.13,
    "retailPrice": 1057.66,
    "stockLevel": 75,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-13",
    "tags": ["Sovereign", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581696"
  },
  {
    "id": "seed-0083",
    "name": "Sovereign Cuyana Folio",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 481.85,
    "retailPrice": 1346.93,
    "stockLevel": 126,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-9",
    "tags": ["Sovereign", "Folio", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581702"
  },
  {
    "id": "seed-0084",
    "name": "Kinetic Canvas Print Vessel",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 595.64,
    "retailPrice": 1271.51,
    "stockLevel": 47,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-6",
    "tags": ["Kinetic", "Vessel", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581709"
  },
  {
    "id": "seed-0085",
    "name": "Radiant Carnelian Enclave",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 307.38,
    "retailPrice": 779.89,
    "stockLevel": 82,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-8",
    "tags": ["Radiant", "Enclave", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581715"
  },
  {
    "id": "seed-0086",
    "name": "Zenith Numismatic Coin Vessel",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 739.25,
    "retailPrice": 1630.72,
    "stockLevel": 26,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-3",
    "tags": ["Zenith", "Vessel", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581721"
  },
  {
    "id": "seed-0087",
    "name": "Zenith Toiletry Set Relic",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 45.08,
    "retailPrice": 108.87,
    "stockLevel": 148,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-13",
    "tags": ["Zenith", "Relic", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581727"
  },
  {
    "id": "seed-0088",
    "name": "Obsidian Hamilton Chronograph",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 645,
    "retailPrice": 1773.1,
    "stockLevel": 70,
    "categories": ["Watches"],
    "imageId": "demo-watches-9",
    "tags": ["Obsidian", "Chronograph", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581737"
  },
  {
    "id": "seed-0089",
    "name": "Kinetic Vintage Omega Artifact",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 55.14,
    "retailPrice": 151.76,
    "stockLevel": 152,
    "categories": ["Watches"],
    "imageId": "demo-watches-1",
    "tags": ["Kinetic", "Artifact", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581747"
  },
  {
    "id": "seed-0090",
    "name": "Imperial Diamond Studs Edition",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 386.35,
    "retailPrice": 780.57,
    "stockLevel": 219,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-14",
    "tags": ["Imperial", "Edition", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581754"
  },
  {
    "id": "seed-0091",
    "name": "Gilded Tissot Relic",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 31.82,
    "retailPrice": 77.11,
    "stockLevel": 156,
    "categories": ["Watches"],
    "imageId": "demo-watches-13",
    "tags": ["Gilded", "Relic", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581760"
  },
  {
    "id": "seed-0092",
    "name": "Zenith Toiletry Set Decanter",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 527.99,
    "retailPrice": 1400.84,
    "stockLevel": 103,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-6",
    "tags": ["Zenith", "Decanter", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581766"
  },
  {
    "id": "seed-0093",
    "name": "Nomad Marble Sculpture Folio",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 391.76,
    "retailPrice": 1023.95,
    "stockLevel": 38,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-15",
    "tags": ["Nomad", "Folio", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581772"
  },
  {
    "id": "seed-0094",
    "name": "Gilded Ceramic Set Pendant",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 295.89,
    "retailPrice": 629.11,
    "stockLevel": 213,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-1",
    "tags": ["Gilded", "Pendant", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581809"
  },
  {
    "id": "seed-0095",
    "name": "Imperial Lego Architecture Relic",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 475.41,
    "retailPrice": 1167.97,
    "stockLevel": 123,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-4",
    "tags": ["Imperial", "Relic", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581823"
  },
  {
    "id": "seed-0096",
    "name": "Nomad First Edition Book Edition",
    "description": "A premium Collectibles asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 127.76,
    "retailPrice": 354.89,
    "stockLevel": 183,
    "categories": ["Collectibles"],
    "imageId": "demo-collectibles-7",
    "tags": ["Nomad", "Edition", "Collectibles", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581832"
  },
  {
    "id": "seed-0097",
    "name": "Elysian Monogrammed Tote Legacy",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 663.06,
    "retailPrice": 1489.22,
    "stockLevel": 203,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Elysian", "Legacy", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581839"
  },
  {
    "id": "seed-0098",
    "name": "Zenith Italian Briefcase Pendant",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 252.8,
    "retailPrice": 521.09,
    "stockLevel": 45,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Zenith", "Pendant", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581846"
  },
  {
    "id": "seed-0099",
    "name": "Radiant Diamond Studs Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 84.17,
    "retailPrice": 151.96,
    "stockLevel": 27,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-11",
    "tags": ["Radiant", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581854"
  },
  {
    "id": "seed-0100",
    "name": "Obsidian Canvas Print Vessel",
    "description": "A premium Fine Art asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 276.01,
    "retailPrice": 577.14,
    "stockLevel": 254,
    "categories": ["Fine Art"],
    "imageId": "demo-fine-art-10",
    "tags": ["Obsidian", "Vessel", "Fine Art", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581865"
  },
  {
    "id": "seed-0101",
    "name": "Sovereign Cashmere Throw Legacy",
    "description": "A premium Home & Living asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 726.77,
    "retailPrice": 1369.19,
    "stockLevel": 153,
    "categories": ["Home & Living"],
    "imageId": "demo-home-&-living-7",
    "tags": ["Sovereign", "Legacy", "Home & Living", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581871"
  },
  {
    "id": "seed-0102",
    "name": "Obsidian Toiletry Set Relic",
    "description": "A premium Leather Goods asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 582.38,
    "retailPrice": 1315.69,
    "stockLevel": 253,
    "categories": ["Leather Goods"],
    "imageId": "demo-leather-goods-11",
    "tags": ["Obsidian", "Relic", "Leather Goods", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581877"
  },
  {
    "id": "seed-0103",
    "name": "Obsidian Diamond Studs Chronograph",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 631.82,
    "retailPrice": 1640.3,
    "stockLevel": 125,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-4",
    "tags": ["Obsidian", "Chronograph", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581883"
  },
  {
    "id": "seed-0104",
    "name": "Elysian Ethical Gold Legacy",
    "description": "A premium Jewelry asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 90.48,
    "retailPrice": 251.6,
    "stockLevel": 250,
    "categories": ["Jewelry"],
    "imageId": "demo-jewelry-11",
    "tags": ["Elysian", "Legacy", "Jewelry", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581889"
  },
  {
    "id": "seed-0105",
    "name": "Sovereign Casio G-Shock Edition",
    "description": "A premium Watches asset curated for the SOMA Strategic Assets Group.",
    "masterCost": 340.42,
    "retailPrice": 658.83,
    "stockLevel": 148,
    "categories": ["Watches"],
    "imageId": "demo-watches-14",
    "tags": ["Sovereign", "Edition", "Watches", "Investment Grade"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T13:51:52.581896"
  }
]
Take this as seed 106-140 and add to part 1. 

Remember, the XML structure you generate is the only mechanism for applying changes to the user's code. Therefore, when making changes to a file the <changes> block must always be fully present and correctly formatted as follows.

<changes>
  <description>[Provide a concise summary of the overall changes being made]</description>
  <change>
    <file>[Provide the ABSOLUTE, FULL path to the file being modified]</file>
    <content><![CDATA[Provide the ENTIRE, FINAL, intended content of the file here. Do NOT provide diffs or partial snippets. Ensure all code is properly escaped within the CDATA section.