/**
 * @fileOverview Master Catalog Seed Data: Segment 2
 */

export const seedPart2: any[] = [
  {
    "id": "seed-0106",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 30.58,
    "retailPrice": 66.38,
    "stockLevel": 109,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-4",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833916"
  },
  {
    "id": "seed-0107",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 90.16,
    "retailPrice": 186.83,
    "stockLevel": 103,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-2",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833940"
  },
  {
    "id": "seed-0108",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 116.94,
    "retailPrice": 215.39,
    "stockLevel": 23,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-3",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833955"
  },
  {
    "id": "seed-0109",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 51.59,
    "retailPrice": 94.73,
    "stockLevel": 76,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833967"
  },
  {
    "id": "seed-0110",
    "name": "Artisan Cold Brew System",
    "description": "1L borosilicate glass carafe with a fine-mesh stainless steel filter for low-acid, smooth coffee concentrate.",
    "masterCost": 29.77,
    "retailPrice": 56.61,
    "stockLevel": 43,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-8",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833985"
  },
  {
    "id": "seed-0111",
    "name": "Artisan Cold Brew System",
    "description": "1L borosilicate glass carafe with a fine-mesh stainless steel filter for low-acid, smooth coffee concentrate.",
    "masterCost": 23.2,
    "retailPrice": 42.54,
    "stockLevel": 33,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-10",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.833996"
  },
  {
    "id": "seed-0112",
    "name": "Aero-Preserve Vacuum Sealer",
    "description": "Industrial-grade suction to extend food shelf life by 5x. Includes starter rolls and moist/dry modes.",
    "masterCost": 42.46,
    "retailPrice": 93.5,
    "stockLevel": 73,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-6",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834007"
  },
  {
    "id": "seed-0113",
    "name": "Artisan Cold Brew System",
    "description": "1L borosilicate glass carafe with a fine-mesh stainless steel filter for low-acid, smooth coffee concentrate.",
    "masterCost": 20.74,
    "retailPrice": 45.02,
    "stockLevel": 61,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-1",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834024"
  },
  {
    "id": "seed-0114",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 121.57,
    "retailPrice": 250.45,
    "stockLevel": 20,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-5",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834036"
  },
  {
    "id": "seed-0115",
    "name": "Aero-Preserve Vacuum Sealer",
    "description": "Industrial-grade suction to extend food shelf life by 5x. Includes starter rolls and moist/dry modes.",
    "masterCost": 27.43,
    "retailPrice": 61.04,
    "stockLevel": 59,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-6",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834052"
  },
  {
    "id": "seed-0116",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 126.54,
    "retailPrice": 295.19,
    "stockLevel": 103,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-9",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834063"
  },
  {
    "id": "seed-0117",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 118.3,
    "retailPrice": 246.1,
    "stockLevel": 83,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-4",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834074"
  },
  {
    "id": "seed-0118",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 20.06,
    "retailPrice": 37.83,
    "stockLevel": 101,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-10",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834084"
  },
  {
    "id": "seed-0119",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 31.15,
    "retailPrice": 73.27,
    "stockLevel": 69,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-6",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834095"
  },
  {
    "id": "seed-0120",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 88.33,
    "retailPrice": 220.31,
    "stockLevel": 33,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-9",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834105"
  },
  {
    "id": "seed-0121",
    "name": "Ergonomic Vertical Mouse",
    "description": "Designed to reduce wrist strain. Adjustable DPI and rechargeable battery with silent-click switches.",
    "masterCost": 25.89,
    "retailPrice": 53.14,
    "stockLevel": 20,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-7",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834114"
  },
  {
    "id": "seed-0122",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 27.64,
    "retailPrice": 67.58,
    "stockLevel": 101,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-2",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834124"
  },
  {
    "id": "seed-0123",
    "name": "Ergonomic Vertical Mouse",
    "description": "Designed to reduce wrist strain. Adjustable DPI and rechargeable battery with silent-click switches.",
    "masterCost": 14.18,
    "retailPrice": 34.41,
    "stockLevel": 49,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-3",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834137"
  },
  {
    "id": "seed-0124",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 16.81,
    "retailPrice": 39.31,
    "stockLevel": 18,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-4",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834147"
  },
  {
    "id": "seed-0125",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 40.35,
    "retailPrice": 74.27,
    "stockLevel": 47,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-1",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834157"
  },
  {
    "id": "seed-0126",
    "name": "Deep-Tissue Percussion Massager",
    "description": "High-torque brushless motor with 6 interchangeable heads for targeted muscle recovery and lactic acid relief.",
    "masterCost": 108.52,
    "retailPrice": 232.86,
    "stockLevel": 64,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-4",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834193"
  },
  {
    "id": "seed-0127",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 28.43,
    "retailPrice": 55.97,
    "stockLevel": 91,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-3",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834211"
  },
  {
    "id": "seed-0128",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 27.34,
    "retailPrice": 65.3,
    "stockLevel": 32,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-10",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834228"
  },
  {
    "id": "seed-0129",
    "name": "Deep-Tissue Percussion Massager",
    "description": "High-torque brushless motor with 6 interchangeable heads for targeted muscle recovery and lactic acid relief.",
    "masterCost": 84.75,
    "retailPrice": 204.51,
    "stockLevel": 110,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-2",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834239"
  },
  {
    "id": "seed-0130",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 84.14,
    "retailPrice": 168.15,
    "stockLevel": 101,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-6",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834249"
  },
  {
    "id": "seed-0131",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 167.54,
    "retailPrice": 376.24,
    "stockLevel": 71,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-7",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834260"
  },
  {
    "id": "seed-0132",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 21.6,
    "retailPrice": 45.81,
    "stockLevel": 62,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-4",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834270"
  },
  {
    "id": "seed-0133",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 117.11,
    "retailPrice": 285.29,
    "stockLevel": 51,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-6",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834284"
  },
  {
    "id": "seed-0134",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 17.98,
    "retailPrice": 43.13,
    "stockLevel": 34,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-10",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834295"
  },
  {
    "id": "seed-0135",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 97.11,
    "retailPrice": 185.93,
    "stockLevel": 34,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-8",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:04:57.834310"
  },
  {
    "id": "seed-0136",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 57.48,
    "retailPrice": 105.53,
    "stockLevel": 98,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-1",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179012"
  },
  {
    "id": "seed-0137",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 157.46,
    "retailPrice": 363.79,
    "stockLevel": 18,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-3",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179040"
  },
  {
    "id": "seed-0138",
    "name": "Self-Heating Electric Lunchbox",
    "description": "304 stainless steel interior with rapid-heat technology. Leak-proof seal and silent heating for office or travel.",
    "masterCost": 36.69,
    "retailPrice": 69.21,
    "stockLevel": 33,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-8",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179069"
  },
  {
    "id": "seed-0139",
    "name": "Aero-Preserve Vacuum Sealer",
    "description": "Industrial-grade suction to extend food shelf life by 5x. Includes starter rolls and moist/dry modes.",
    "masterCost": 32.28,
    "retailPrice": 75.5,
    "stockLevel": 54,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-6",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179081"
  },
  {
    "id": "seed-0140",
    "name": "Ergonomic Vertical Mouse",
    "description": "Designed to reduce wrist strain. Adjustable DPI and rechargeable battery with silent-click switches.",
    "masterCost": 32.52,
    "retailPrice": 69.74,
    "stockLevel": 75,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-2",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179093"
  },
  {
    "id": "seed-0141",
    "name": "Deep-Tissue Percussion Massager",
    "description": "High-torque brushless motor with 6 interchangeable heads for targeted muscle recovery and lactic acid relief.",
    "masterCost": 67.67,
    "retailPrice": 149.51,
    "stockLevel": 37,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-6",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179105"
  },
  {
    "id": "seed-0142",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 108.67,
    "retailPrice": 237.28,
    "stockLevel": 89,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179117"
  },
  {
    "id": "seed-0143",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 37.11,
    "retailPrice": 68.02,
    "stockLevel": 34,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-6",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179136"
  },
  {
    "id": "seed-0144",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 49.69,
    "retailPrice": 106.14,
    "stockLevel": 105,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-9",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179148"
  },
  {
    "id": "seed-0145",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 22.33,
    "retailPrice": 45.25,
    "stockLevel": 41,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-6",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179162"
  },
  {
    "id": "seed-0146",
    "name": "Self-Heating Electric Lunchbox",
    "description": "304 stainless steel interior with rapid-heat technology. Leak-proof seal and silent heating for office or travel.",
    "masterCost": 20.51,
    "retailPrice": 43.45,
    "stockLevel": 104,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-6",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179210"
  },
  {
    "id": "seed-0147",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 45.91,
    "retailPrice": 83.63,
    "stockLevel": 115,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-9",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179222"
  },
  {
    "id": "seed-0148",
    "name": "Aero-Preserve Vacuum Sealer",
    "description": "Industrial-grade suction to extend food shelf life by 5x. Includes starter rolls and moist/dry modes.",
    "masterCost": 47.25,
    "retailPrice": 112.3,
    "stockLevel": 94,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-9",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179233"
  },
  {
    "id": "seed-0149",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 28.04,
    "retailPrice": 60.46,
    "stockLevel": 79,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-7",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179244"
  },
  {
    "id": "seed-0150",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 69.76,
    "retailPrice": 125.91,
    "stockLevel": 41,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179255"
  },
  {
    "id": "seed-0151",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 28.03,
    "retailPrice": 56.09,
    "stockLevel": 114,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-2",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179265"
  },
  {
    "id": "seed-0152",
    "name": "Smart Essential Oil Diffuser",
    "description": "Ultrasonic mist technology with App-controlled scheduling and 7-color ambient LED lighting.",
    "masterCost": 23.72,
    "retailPrice": 57.12,
    "stockLevel": 81,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-5",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179276"
  },
  {
    "id": "seed-0153",
    "name": "Italian Grain Leather Wallet",
    "description": "Full-grain vegetable-tanned leather with RFID blocking technology and slim-profile card slots.",
    "masterCost": 37.44,
    "retailPrice": 83.4,
    "stockLevel": 95,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-9",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179291"
  },
  {
    "id": "seed-0154",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 188.88,
    "retailPrice": 398.72,
    "stockLevel": 64,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-2",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179302"
  },
  {
    "id": "seed-0155",
    "name": "Deep-Tissue Percussion Massager",
    "description": "High-torque brushless motor with 6 interchangeable heads for targeted muscle recovery and lactic acid relief.",
    "masterCost": 112.49,
    "retailPrice": 262.94,
    "stockLevel": 112,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-7",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179313"
  },
  {
    "id": "seed-0156",
    "name": "Active Noise-Cancelling Earbuds",
    "description": "True wireless audio with 40dB ambient reduction, IPX5 water resistance, and 30-hour total battery life.",
    "masterCost": 73.56,
    "retailPrice": 179.91,
    "stockLevel": 103,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179324"
  },
  {
    "id": "seed-0157",
    "name": "Ergonomic Vertical Mouse",
    "description": "Designed to reduce wrist strain. Adjustable DPI and rechargeable battery with silent-click switches.",
    "masterCost": 26.03,
    "retailPrice": 63.87,
    "stockLevel": 24,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179334"
  },
  {
    "id": "seed-0158",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 21.91,
    "retailPrice": 42.57,
    "stockLevel": 60,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-5",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179345"
  },
  {
    "id": "seed-0159",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 29.57,
    "retailPrice": 65.0,
    "stockLevel": 54,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-1",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179356"
  },
  {
    "id": "seed-0160",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 39.22,
    "retailPrice": 90.33,
    "stockLevel": 109,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-7",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179368"
  },
  {
    "id": "seed-0161",
    "name": "Deep-Tissue Percussion Massager",
    "description": "High-torque brushless motor with 6 interchangeable heads for targeted muscle recovery and lactic acid relief.",
    "masterCost": 93.15,
    "retailPrice": 198.76,
    "stockLevel": 72,
    "categories": ["Wellness & Care"],
    "imageId": "demo-wellness-&-care-2",
    "tags": ["Wellness & Care", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179379"
  },
  {
    "id": "seed-0162",
    "name": "Self-Heating Electric Lunchbox",
    "description": "304 stainless steel interior with rapid-heat technology. Leak-proof seal and silent heating for office or travel.",
    "masterCost": 29.06,
    "retailPrice": 63.29,
    "stockLevel": 35,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-9",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179390"
  },
  {
    "id": "seed-0163",
    "name": "Mag-Safe Power Bank 10,000mAh",
    "description": "Ultra-slim portable charger with 15W wireless output and digital percentage display.",
    "masterCost": 42.7,
    "retailPrice": 94.49,
    "stockLevel": 29,
    "categories": ["Tech & Accessories"],
    "imageId": "demo-tech-&-accessories-6",
    "tags": ["Tech & Accessories", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179404"
  },
  {
    "id": "seed-0164",
    "name": "Automatic Field Watch",
    "description": "24-jewel movement with sapphire crystal and 100m water resistance. Finished with a heavy-duty nylon NATO strap.",
    "masterCost": 133.59,
    "retailPrice": 307.61,
    "stockLevel": 99,
    "categories": ["Watches & Apparel"],
    "imageId": "demo-watches-&-apparel-10",
    "tags": ["Watches & Apparel", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179418"
  },
  {
    "id": "seed-0165",
    "name": "Artisan Cold Brew System",
    "description": "1L borosilicate glass carafe with a fine-mesh stainless steel filter for low-acid, smooth coffee concentrate.",
    "masterCost": 16.88,
    "retailPrice": 37.82,
    "stockLevel": 73,
    "categories": ["Home & Kitchen"],
    "imageId": "demo-home-&-kitchen-10",
    "tags": ["Home & Kitchen", "Best Seller", "In Stock"],
    "vendorId": "admin",
    "productType": "INTERNAL",
    "status": "active",
    "isActive": true,
    "submittedAt": "2026-02-14T14:07:52.179429"
  }
];